[pytest]
minversion = 6.0
addopts = -v -s --tb=short
testpaths = 04_lesson
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    positive: Позитивные тесты
    negative: Негативные тесты
    